- type: job
  id: CaesarLegionPraefectusDecanus
  setPreference: true
  hideWithoutJobWhitelist: false # #Misfits Tweak - accessible up to Vet Decanus, no whitelist
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - all jobs visible in selection
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 150
  showBorder: true
  name: job-name-caesar-legion-praefectus-decanus
  description: job-description-caesar-legion-praefectus-decanus
  playTimeTracker: CaesarLegionPraefectusDecanus
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: CaesarLegionVeteranDecanus
      min: 100000 # 30 hours for the big vet pa role
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterSexRequirement
      sex: Male
    - !type:CharacterGenderRequirement
      gender: Male
  startingGear: CaesarLegionVeteranDecanusGear
  alwaysUseSpawner: true
  icon: "JobIconlegionerDean"
  supervisors: job-name-caesar-legion-supervisors
  canBeAntag: false
  accessGroups:
  - CaesarLegionVeteranDecanus
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaesarLegion
      - type: ReplacementAccent
        accent: latin
      - type: Warcry
        action: ActionLegionWarcry
        targetDepartment: CaesarLegion
        range: 6
        speedBonus: 0.30 # #Misfits Tweak - reduced from 0.50, was too strong
        duration: 10
        overlayColor: "#D64545"
        speechVerb: MisfitsLegionWarcry
        warcryMessage: warcry-message-legion
        warcryMessageCount: 6
        buffPopup: warcry-popup-buffed-legion
        excludedJobs:
        - SuperMutantGladiator
        cautionPopup: true
        activatorJobs:
        - CaesarLegionVexillarius
        - CaesarLegionDean
        - CaesarLegionPrimeDecanus
        - CaesarLegionVeteranDecanus
        - CaesarLegionCenturion
        - CaesarLegionLegate
        - CaesarLegionOptio
        - CaesarLegionPriestessOfMars
        - CaesarLegionPraefectusDecanus
        - CaesarLegionTribunusDecanus
  - !type:AddTraitSpecial
    traits: [ LanguageLatin ]

- type: startingGear
  id: CaesarLegionPraefectusDecanusGear
  equipment:
    wallet: N14Wallet
    jumpsuit: N14ClothingUniformJumpsuitLegionnaire
    ears: N14ClothingHeadsetLegion
    neck: ClothingNeckRedScarf
    eyes: N14ClothingEyesGlassesWelding
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    head: N14ClothingHeadHatDeanVeteranHelmet
    gloves: N14ClothingHandsGlovesTribal
    outerClothing: N14ClothingOuterPowerArmorLegionPrinceps # whole point of tribunus and praefectus roles
    belt: N14Gladius
    pocket1: LegionDeanloadoutkits
    id: N14IDLegionaryMedalVeteranDecanus
  innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther
  storage:
    back:
    - N14BoxPlasticFilledMilitaryLegion #Misfits Change /Tweak/: Legion uses tribal medicine, not stimpaks
    - N14HealingPowder
    - N14WelderIndustrial # self explainatory for pa user
    - N14ClothingEyesGlassesWelding

- type: playTimeTracker
  id: CaesarLegionPraefectusDecanus
