using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._RMC.Vendors;

/// <summary>
/// Reusable RMC-style catalog row. Presentation and disabled feedback live here so allocation and shared storage
/// cannot drift into separate button layouts.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorEntry : PanelContainer
{
    public CMAutomatedVendorEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public void Configure(
        Texture? icon,
        string name,
        string description,
        string details,
        string? disabledReason,
        string actionText,
        Action onPressed)
    {
        ItemIcon.Texture = icon;
        NameLabel.Text = name;
        DetailLabel.Text = disabledReason ?? details;
        DetailLabel.ModulateSelfOverride = disabledReason == null ? Color.LightGray : Color.OrangeRed;
        ActionButton.Text = actionText;
        ActionButton.Disabled = disabledReason != null;
        ActionButton.ToolTip = disabledReason ?? description;
        ActionButton.OnPressed += _ => onPressed();
        ToolTip = description;
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = disabledReason == null ? Color.FromHex("#162031") : Color.FromHex("#282D35"),
            BorderColor = Color.FromHex("#4972A1"),
            BorderThickness = new Thickness(2),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 5,
            ContentMarginBottomOverride = 5,
        };
    }
}
