using Content.Shared._Misfits.WastelandMap;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.WastelandMap;

[GenerateTypedNameReferences]
public sealed partial class MapPinManageWindow : DefaultWindow
{
    public event Action<NetEntity>? OnRemove;
    public event Action<string>? OnCreate;

    public MapPinManageWindow()
    {
        RobustXamlLoader.Load(this);
        CreateButton.OnPressed += _ => ShowCreate();
        CancelButton.OnPressed += _ => ShowList();
        SubmitButton.OnPressed += _ => Submit();
        NameInput.OnTextEntered += _ => Submit();
    }

    private void ShowCreate()
    {
        NameInput.Text = string.Empty;
        ManagePanel.Visible = false;
        CreatePanel.Visible = true;
    }

    private void ShowList()
    {
        CreatePanel.Visible = false;
        ManagePanel.Visible = true;
    }

    private void Submit()
    {
        var name = NameInput.Text.Trim();
        if (name.Length == 0)
            return;

        OnCreate?.Invoke(name);
        ShowList();
    }

    public void SetPins(GlobalMapPinEntry[] pins)
    {
        PinList.RemoveAllChildren();
        if (pins.Length == 0)
        {
            PinList.AddChild(new Label { Text = Loc.GetString("mappin-manage-empty") });
            return;
        }

        foreach (var pin in pins)
        {
            var captured = pin.Pin;
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            row.AddChild(new Label { Text = $"{pin.Label}  ({MathF.Round(pin.X)}, {MathF.Round(pin.Y)})", HorizontalExpand = true });
            var remove = new Button { Text = Loc.GetString("mappin-manage-remove"), StyleClasses = { "Caution" } };
            remove.OnPressed += _ => OnRemove?.Invoke(captured);
            row.AddChild(remove);
            PinList.AddChild(row);
        }
    }
}

[UsedImplicitly]
public sealed class MapPinManageBoundUserInterface : BoundUserInterface
{
    private MapPinManageWindow? _window;
    public MapPinManageBoundUserInterface(EntityUid owner, Enum key) : base(owner, key) { }

    protected override void Open()
    {
        base.Open();
        _window = this.CreateWindow<MapPinManageWindow>();
        _window.OnRemove += pin => SendMessage(new MapPinRemoveMessage(pin));
        _window.OnCreate += name => SendMessage(new MapPinNameMessage(name));
    }

    protected override void UpdateState(BoundUserInterfaceState state)
    {
        if (state is MapPinManageState pins)
            _window?.SetPins(pins.Pins);
    }
}
